<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

    <h3>Okay. Let's talk!</h3>

	   <section class="container" id="social">
            <a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-snapchat-ghost"></i></a>
        </section>

<hr>
    <form class="contact-form" action="<?php echo $_SERVER['PHP_SELF']?>" method="POST">

       <fieldset>
           <legend>Want me to get back to you?</legend>

           <ul>
               <li>
                   <label for="firstName">Prénom :</label>
                   <input type="text" name="firstname" id="firstName" autofocus>
               </li>
               <li>
                   <label for="email">E-mail :</label>
                   <input type="email" name="email" id="email">
               </li>
               <li>
                   <label for="subject">Objet :</label>
                   <input type="text" name="subject" id="subject">
               </li>
               <li>
                   <label for="message">Message :</label>
                   <textarea id="message" name="message" rows="10"></textarea>
               </li>
               <li>
                   <button type="submit" name="submit">Envoyer</button>
                   <a href="index.php" class="cancel">Annuler</a>
               </li>
           </ul>
       </fieldset>
    </form>
</body>
</html>