<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<section id="hello">
		<article>
			<p>Hello! Ici, je te fait découvrir mes créations originales. </p>

			<p>Originales?! Oui, originales car je les réalise entièrement; de l'idée au produit fini. Mes crèmes glacées sont toutes artisanales. Je travaille chaque idée jusqu'à obtenir entière satisfaction. Je choisis les parfums, la composition; ajuste les dosages et la texture. Je privilégie des produits habituellement peu ou pas exploités afin d'apporter du renouveau dans l'univers de la glace. </p>

			<p>Toutes mes réalisations sont à base de produits bios. Je ne présente ici que les produits auxquels je crois et qui, plus important encore, ont reçu l'aval de mon jury d'experts: mes amis et ma famille!</p>
		</article>
	</section>


		<figure id="slider" class="slider">
            <h3>Découvre mes créations originales</h3>
                <nav class="toolbar">
                    <ul class="button">
                        <li><button id="slider-previous" title="Image précédente"><i class="fa fa-backward"></i></button></li>
                        <li><button id="slider-toggle" title="Démarrer le carrousel"><i class="fa fa-play"></i></button></li>
                        <li><button id="slider-next" title="Image suivante"><i class="fa fa-forward"></i></button></li>
                    </ul>
                </nav>
           <a href="show_work.php"><img src="" alt="Photo du carrousel"></a>
            <figcaption></figcaption>
        </figure>

			

</body>
</html>