<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<section id="container">
		
		<?php foreach ($showCreations as $creation) : ?>
			<article class="glace">
				<h3>
					 <?= htmlspecialchars($creation['Name'])?>
				</h3>

				<img src="images/glaces/<?= ($creation['Photo']) ?>" alt="<?=htmlspecialchars($creation['Name']) ?>">

				<p><?=htmlspecialchars($creation['Description'])?></p>

				<p><span>Bon à savoir : </span><?= htmlspecialchars($creation['Anecdote']) ?> &nbsp; 
				</p>

				<a href="show_description.php?id=<?= intval ($creation['Id'])?>" title="Coup d'oeil sur la création"><i class="fas fa-plus-circle"></i></a>
				
			</article>
		<?php endforeach; ?>	
	</section>
</body>
</html>