<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<section id="container">
		
		<img src="./images/Elsa.jpg" alt="Elsa" class="image">

		<p>Je suis Elsa, une jeune entrepreneure passionnée par mon métier de glacier qui n'est pourtant pas le métier auquel je me destinais dans un premier temps. 
		Mon parcours est tout à la fois singulier et commun. Je me suis lancée dans ce métier suite à une reconversion professionnelle.</p>

		<p>Fan de nourriture en général et de sucreries en particulier, je dois bien l'avouer, j'ai d'abord passé on CAP Pâtisserie que j'ai ensuite complété avec la formation de CAP Glacier.</p>

		<p>En grande passionnée de crèmes glacées, je me lance aujourd'hui dans une nouvelle aventure, je crée ma propre marque de crème glacée avec pour ambition de créer des crèmes glacées inédites en termes de goûts et textures.</p>

		<p>J'essaie autant que possible de travailler des produits exotiques tels que la goyave, la banane, le manioc, l'ananas... mais aussi des matières moins originales telles que le chocolat, la vanille, la pistache ou encore la cacahuète.</p>

		<p>Je te laisse donc découvrir mon univers et j'espère qu'il te plaira !</p>

		<p>Si c'est le cas n'hésite pas à me laisser un petit commentaire. 
		</p>
			
	</section>
</body>
</html>